export const QueryKey = {
  GET_ALL_SERVICE: "GET_ALL_SERVICE",
  GET_SERVICE_BY_ID: "GET_SERVICE_BY_ID",
  GET_ALL_CATEGORY: "GET_ALL_CATEGORY",
  GET_ALL_SUBCATEGORY: "GET_ALL_SUBCATEGORY",
  GET_ALL_STAFF: "GET_ALL_STAFF",

  GET_USER_BY_EMAIL: "GET_USER_BY_EMAIL",
  GET_USER_BY_PHONE: "GET_USER_BY_PHONE",
  GET_USER_BY_USERNAME: "GET_USER_BY_USERNAME",
  GET_USER_BY_ROLE: "GET_USER_BY_ROLE",
  GET_USER_BY_STATUS: "GET_USER_BY_STATUS",
  GET_USER_BY_CREATED_AT: "GET_USER_BY_CREATED_AT",
  GET_USER_BY_UPDATED_AT: "GET_USER_BY_UPDATED_AT",
  GET_USER_BY_DELETED_AT: "GET_USER_BY_DELETED_AT",
};
